### PR TITLE
Morrigan/build fix

### LINKED ISSUE #49: Running build without arguments returns error
Screenshot 2020-03-09 at 13 37 31

Expected behavior: prints helps

### PR DESCRIPTION
**Pull request by morrigan**
Config load fix
Resolves #49

### CODE REVIEW

File: main.go [hunk 1]
```diff
@@ -16,7 +16,9 @@ func main() {
 
 	command := os.Args[1:]
 	// special handling needed if start command called
-	if command[0] == "start" {
+	if len(os.Args) <= 1 {
```
Comment (MakMuftic) [inline main.go:19]: :clap:

**Review by MakMuftic — APPROVED** [review]
Seems good for now :smile:
